apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-oidc-cm
  namespace: gitops
data:
  url: https://auth.example.com
  clientID: argocd
  clientSecret: ""
  requestedScopes: openid,profile,email
  requestedIDTokenClaims: |
    groups:
      essential: true
      friendlyName: groups
